// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	models "github.com/PIRSON21/parking/internal/models"
	mock "github.com/stretchr/testify/mock"

	parking "github.com/PIRSON21/parking/internal/http-server/handler/parking"
)

// ParkingSetter is an autogenerated mock type for the ParkingSetter type
type ParkingSetter struct {
	mock.Mock
}

// AddParking provides a mock function with given fields: _a0
func (_m *ParkingSetter) AddParking(_a0 *models.Parking) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddParking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Parking) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteParking provides a mock function with given fields: _a0
func (_m *ParkingSetter) DeleteParking(_a0 int) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParking provides a mock function with given fields: _a0, _a1
func (_m *ParkingSetter) UpdateParking(_a0 *parking.ParkingPatch, _a1 []*models.ParkingCellStruct) (*models.Parking, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParking")
	}

	var r0 *models.Parking
	var r1 error
	if rf, ok := ret.Get(0).(func(*parking.ParkingPatch, []*models.ParkingCellStruct) (*models.Parking, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*parking.ParkingPatch, []*models.ParkingCellStruct) *models.Parking); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Parking)
		}
	}

	if rf, ok := ret.Get(1).(func(*parking.ParkingPatch, []*models.ParkingCellStruct) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewParkingSetter creates a new instance of ParkingSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingSetter {
	mock := &ParkingSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
