// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthGetter is an autogenerated mock type for the AuthGetter type
type AuthGetter struct {
	mock.Mock
}

// GetUserID provides a mock function with given fields: sessionID
func (_m *AuthGetter) GetUserID(sessionID string) (int, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthGetter creates a new instance of AuthGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthGetter {
	mock := &AuthGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
